Examples 2 and 3

In [1]:
# load the libraries we'll need
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import sys
np.set_printoptions(suppress=True)

In [9]:
# create random input data
x_input = np.random.uniform(size=(1,10)).astype(np.float32)
W = tf.Variable(tf.random.uniform([10,2]),name='W')
b = tf.Variable(tf.ones([2]),name='b')

In [3]:
# perform a simple operation
def multiply_add(x):
    return tf.matmul(x,W) + b

In [4]:
# make the calculation
y = multiply_add(x_input)

In [12]:
print(x_input)

[[0.8976681  0.6833673  0.32689324 0.49193323 0.5466849  0.5559122
  0.96683025 0.12782235 0.95931715 0.94087327]]


In [5]:
# print the variables and the result of the calculation
print(b.numpy())

[1. 1.]


In [6]:
print(W.numpy())

[[0.883178   0.642149  ]
 [0.49885058 0.7298292 ]
 [0.45937717 0.43429887]
 [0.7481575  0.5131844 ]
 [0.60794556 0.12127113]
 [0.16030061 0.8108101 ]
 [0.5884304  0.700251  ]
 [0.32095027 0.71855915]
 [0.65981424 0.5615494 ]
 [0.23467839 0.76206386]]


In [7]:
print(y.numpy())

[[3.1789548 3.7212949]]


### Using graph node

#### First, we’ll use eager mode again to make a slightly different calculation

In [14]:
# create a new variable
b_init = tf.Variable(tf.ones([2]),name='b_init')

# perform the operation in a loop
def multiply_add(x,b):
    for i in range(5):
        output = tf.matmul(x,W) + b
        # increase the value of b
        b = tf.add(output, b)
        # here we print the offset b which will change values within the loop
        print(b)
    return output

In [15]:
# run the function that will execute the for-loop
y = multiply_add(x_input,b_init)

tf.Tensor([[5.936059 4.514458]], shape=(1, 2), dtype=float32)
tf.Tensor([[15.808177 11.543375]], shape=(1, 2), dtype=float32)
tf.Tensor([[35.552414 25.601208]], shape=(1, 2), dtype=float32)
tf.Tensor([[75.040886 53.716873]], shape=(1, 2), dtype=float32)
tf.Tensor([[154.01782  109.948204]], shape=(1, 2), dtype=float32)


### Next, we’ll convert to graph mode by introducing a function decorator

In [17]:
@tf.function
def multiply_add(x,b):
    for i in range(5):
        output = tf.matmul(x,W) + b
        # increase the value of b
        b = tf.add(output, b)
        # here we print the offset b which will change values within the loop
        print(b)
    return output

In [18]:
# run the function that will execute the for-loop
y = multiply_add(x_input,b_init)

Tensor("Add_1:0", shape=(1, 2), dtype=float32)
Tensor("Add_3:0", shape=(1, 2), dtype=float32)
Tensor("Add_5:0", shape=(1, 2), dtype=float32)
Tensor("Add_7:0", shape=(1, 2), dtype=float32)
Tensor("Add_9:0", shape=(1, 2), dtype=float32)


In [ ]:
# the value of the tensor is not displayed

In [19]:
#Plus if we call the function again, we can see that nothing is printed.
y = multiply_add(x_input,b_init)